### ISSUE TITLE
Implement logo-uri, tos-uri and policy-uri

### ISSUE THREAD

**Issue by akselleirv** [ory/hydra-maester#105]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-maester/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-maester/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Please correct me if I'm wrong, but I could not find any mentions of the logo-uri, tos-uri and policy-uri in the CRD.

### Describe your ideal solution

Have it implemented in the operator.

### Workarounds or alternatives

Add it with the CLI, but that would be difficult to maintain in the long run.

### Version

latest

**Comment by Demonsthere** [comment]
Hello there!
Yes, the CRD may miss some options, they do not give 100% coverage at this point 😞
