### ISSUE TITLE
Hydra Maester requesting for secret at cluster scope

### ISSUE THREAD

**Issue by cpwc** [ory/hydra-maester#18]
I am constantly getting maester requesting secret at cluster scope error. Is this a feature or there's a bug in the `RoleBinding` in `ory/k8s` that needs to be fixed?

```
E0906 03:20:19.817318       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
E0906 03:20:20.819535       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
E0906 03:20:21.821676       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
E0906 03:20:22.824112       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
E0906 03:20:23.826419       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
E0906 03:20:24.828602       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
E0906 03:20:25.830754       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
E0906 03:20:26.832843       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:identity-k8s-vidds-ee:hydra-maester-account" cannot list resource "secrets" in API group "" at the cluster scope
```

**Comment by piotrmsc** [comment]
According to https://github.com/ory/k8s/blob/master/helm/charts/hydra/charts/hydra-maester/templates/rbac.yaml#L61 this is definitely a bug :) But in `ory/k8s`.

Other thing is a question whether the controller should list all the secrets at startup, IMO no but  I assume this is automatically done by the dynamic client https://github.com/ory/hydra-maester/blob/master/main.go#L29. Thoughts @jakkab ?

**Comment by cpwc** [comment]
@piotrmsc yeah. I agree that we should not be listing all secrets tho.

**Comment by jakkab** [comment]
Fixed in latest release.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
