### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by paulbdavis** [ory/hydra-maester#27]
I am trying to work on #26 and I am having issues running the tests.

I managed to get it working with my minikube setup, but I am getting the following error:

```
assert: mock: I don't know what to return because the method call was unexpected.
	Either do Mock.On("GetOAuth2Client").Return(...) first, or remove the GetOAuth2Client() call.
	This method was unexpected:
		GetOAuth2Client(string)
		0: "testClientID"
	at: [HydraClientInterface.go:29 oauth2client_controller.go:95 suite_test.go:98 reconcile.go:93 controller.go:216 controller.go:192 controller.go:171 wait.go:152 wait.go:153 wait.go:88 asm_amd64.s:1357]
```

I tried to run `mockery -name=HydraClientInterface` in `controllers/mocks` but it returns the error `Unable to find HydraClientInterface in any go files under this path`

**Comment by aeneasr** [comment]
Did you follow https://github.com/ory/hydra-maester#how-to-use-it ?

**Comment by paulbdavis** [comment]
I did follow that, the initial `make test` is what is failing.

Using the `feature/minikube-test` branch of my repo (in #28), I can get the first test (`api/oauth_2_client_types_test.go`) to run sucessfully with the patches I've added, but I still get the error described in the OP when the second test runs (`controller/suite_test.go`)

To test my changes, I just started a basic minikube cluster on my machine (`minikube start --vm-driver kvm2`) and tried to run the test against that (my fork currently defaults `USE_EXISTING_CLUSTER` to `t` [any non empty value triggers the local cluster] though that bit will be reverted once it's ready)

From the error, it looks like I'm just missing some mock files that need to be generated, but aside from the `mockery -name={INTERFACE_NAME}` in the README (which didn't work, as described in OP) there is no mention of generating any files for the tests to run.

**Comment by aeneasr** [comment]
@jakkab could you maybe help clarify this?

**Comment by jakkab** [comment]
@paulbdavis @aeneasr I'm on it.

**Comment by jakkab** [comment]
@paulbdavis The file containing the target interface (oauth2client_controller.go) is not under controllers/mocks. Try running ```mockery -name=HydraClientInterface``` in the **controllers** dir.

**Comment by jakkab** [comment]
@paulbdavis What's the reason behind switching those tests to minikube?

**Comment by paulbdavis** [comment]
@jakkab It's not just a switch to minikube, but allowing testing on any existing cluster (I just set up minikube for simplicity, since the CRD is in use on my existing clusters). It's enabled by a variable in the makefile though, so the existing test would still be the default (it's enabled by default in my current PR branch, but that would be changed before it's done)

**Comment by paulbdavis** [comment]
> @paulbdavis The file containing the target interface (oauth2client_controller.go) is not under controllers/mocks. Try running `mockery -name=HydraClientInterface` in the **controllers** dir. Anyways, generating new mocks won't do the trick, I'm afraid. Let me dig into it.

I assumed that it was already generated, but I tried again anyway, the only thing that changed in the generated file was the format of the `import` statement.

Either way, I am getting that same error with the newly generated file as well.

**Comment by paulbdavis** [comment]
I finally figured out that I just needed to install kubebuilder to get the default testing to work. I'll just make a PR stating such in the README for simplicity

**Comment by jakkab** [comment]
> I assumed that it was already generated, but I tried again anyway, the only thing that changed in the generated file was the format of the `import` statement.
> 
> Either way, I am getting that same error with the newly generated file as well.

This is correct, no interface has been added meaning no new mocks are required.

**Comment by jakkab** [comment]
@paulbdavis 

> I finally figured out that I just needed to install kubebuilder to get the default testing to work. I'll just make a PR stating such in the README for simplicity

Thank you!
