### ISSUE TITLE
Maester controller

### ISSUE THREAD

**Issue by piotrmsc** [ory/hydra-maester#3]
## Description

Create a controller that will allow registering hydra oatuh2 clients using Custom Resources. 

- store  ID of client, clientID and clientSecret in k8s secret in the same namespace of applied CR
- communicate with hydra over REST with retries
- use kubernetes endpoints to find out all hydra instances

**Comment by jakkab** [comment]
partially implemented in #12, #17 and #19.

todos:
- [ ] implement retries
- [ ] update integration tests

**Comment by p-bakker** [comment]
> implement retries
@jakkab is there anything in the works to implement the retry mechanism for the api calls from maester to Hydra?

> use kubernetes endpoints to find out all hydra instances
@piotrmsc I assume this would just be required for any functionality in the controller to find all Hydra instances (based on namespace of label selectors I presume) to then call the /clients api on each Hydra  instance when CRs get added/updated/removed? And as such, this would be part of for example https://github.com/ory/hydra-maester/issues/4?
