### ISSUE TITLE
hydra_v1alpha1_oauth2client_user_credentials.yaml is using invalid apiVersion for OAuth2Client

### ISSUE THREAD

**Issue by PoulpiFr** [ory/hydra-maester#41]
Apparently, hydra maester once used the hydra.ory.sh/v1alpha2 api-version through 2 PRs #30 and #35.

And after discussion on https://github.com/ory/hydra-maester/pull/30, it was decided to stay on hydra.ory.sh/v1alpha1.

Sadly, one of the sample (https://github.com/ory/hydra-maester/blob/master/config/samples/hydra_v1alpha1_oauth2client_user_credentials.yaml#L11) wasn't properly updated.

**Comment by PoulpiFr** [comment]
Fixed in #42

**Comment by PoulpiFr** [comment]
@paulbdavis & @aeneasr

**Comment by aeneasr** [comment]
thank you, the PR is merged :)
