### ISSUE TITLE
Restarting hydra-maester should trigger a reconcile check

### ISSUE THREAD

**Issue by Demonsthere** [ory/hydra-maester#43]
**Description:**
Currently, as the default mode of operation for hydra is in-memory storage, in the case of hydra restart, all existing clients are purged from its memory. As those clients are seen as "already served", they won't be touched by the controller unless they are updated in some way. This can lead to a situation in which the CRs on the cluster do not represent what is stored in hydra.

**Expectation:**
Restarting hydra-maester should trigger some sort of mechanism that would regenerate the existing clients (from the CRs) and repopulate hydra.

**Comment by jakkab** [comment]
will be handled as a part of #46

**Comment by jakkab** [comment]
@aeneasr With #46 merged, I think we can close this issue.
