### ISSUE TITLE
Reconciliation Broken with Hydra > 1.3

### ISSUE THREAD

**Issue by jhutchins** [ory/hydra-maester#49]
Starting with the introduction of ory/hydra#1707 new clients can no longer be added via a CRD since queries for unknown clients return a 401 response instead of a 404.

**Comment by aeneasr** [comment]
Thanks, triaged. PRs welcome!

**Comment by jhutchins** [comment]
@aeneasr I'm happy to provide a patch. Would you rather handle the issue in hydra-maester or in hydra?

I personally disagree with the change in ory/hydra#1707 because I don't think it makes sense to return a 401 response from an unauthenticated endpoint. The feature has the façade of security, but since it not actually possible to authenticate the confusing response of `401 Unauthenticated` is just a direct one to one mapping to the much more obvious and idiomatic `404 Not Found` response.

All that said, if you want to keep that 401 functionality for whatever reason I can easily fix the issue from the hydra-maester side too. I'm will to follow your lead on how you want it fixed.

**Comment by aeneasr** [comment]
Released as 0.0.15
