### ISSUE TITLE
Is there an option to update hydra clients once secrets are changed?

### ISSUE THREAD

**Issue by mih-kopylov** [ory/hydra-maester#59]
I have a use case: 
* created a secret `my-secret` in namespace
* created a client in hydra using maester, referencing `my-secret`
* updated secret `my-secret` with a new `client_secret` value inside

I expect that maester will update client in hydra, but it obviouly doesn't right now.
Is there a way to do that?

**Comment by aeneasr** [comment]
I think update was implemented, but I might be mistaken. @jakkab do you know?

**Comment by mih-kopylov** [comment]
@aeneasr I've just run through the use-case, but didn't find the client updated in hydra database. Probably there's some parameter for maester, disabled by default, that I've missed?

**Comment by jakkab** [comment]
Hi @mih-kopylov! Please follow this [guide](https://github.com/ory/k8s/blob/master/docs/helm/hydra-maester.md#update-the-oauth2-client-secret) to learn how to update client secrets. For know, we don't support secret discovery in Hydra-maester. Would you be open to work on this?

**Comment by mih-kopylov** [comment]
@jakkab I would do that with great pleasure, but unfortunately I'm not qualified enough in `Go`. 
Thanks for docs. Will keep that in mind.
