### ISSUE TITLE
Oauth2 clients registered in Hydra miss`redirect_uris`

### ISSUE THREAD

**Issue by jakkab** [ory/hydra-maester#60]
Expected behaviour:

Oauth2 clients registered in Hydra have the same values as their corresponding CRs.

Actual behaviour:

The `redirect_uris` field is always empty.

Steps to reproduce:

1. Apply a custom resource with some `RedirectURIs`
2. Inspect the registered client through Hydra API (/clients endpoint)

**Comment by maciej-kapusta** [comment]
If you use `redirectUris` instead of `redirect_uris` it should work. I had similar issue with `post_logout_redirect_uris`.

**Comment by aeneasr** [comment]
Thanks, that seems like an appropriate resolution!
