### ISSUE TITLE
OAuth2 client CRD metadata issue

### ISSUE THREAD

**Issue by taras-strypko** [ory/hydra-maester#71]
Hi folks,

Any reason why in recent release metadata type in `hydra.ory.sh_oauth2clients.yaml` has changed from object to byte string?

**Expected**:

```
   metadata:
      description: Metadata is abritrary data
      type: object
```

**Actual**:
```
   metadata:
      description: Metadata is abritrary data
      format: byte
      type: string
```
The only way I found to set object there is to `base64encode` the json string. But, in our case it breaks IDP, as we should do base64 decoding there. 
And, it also seems that Hydra `/clients` endpoint didn't change in that perspective - metadata is still an object.

Previously, we were able to specify it in our `yaml` like this:
```
metadata:
    type: internal

```
And get response from hydra with appropriate object:
```
 {
   ...
   metadata: {
       'type': 'internal'
   }

```

And now if we want to specify object, we specify base64 encoded json string in yaml:
```
metadata: eyJ0eXBlIjoiaW50ZXJuYWwifQ==

```
And we get it as-is from hydra `/clients` endpoints:
```
 {
   ...
   metadata: "eyJ0eXBlIjoiaW50ZXJuYWwifQ=="
 }
```

Please, let me know if it was done purposely or is maybe some auto-generation issue?
I can do the PR, just let me know if I'm missing some puzzle here.

@colunira @aeneasr @Demonsthere

**Comment by Demonsthere** [comment]
Hello there. If I see correctly this was changed in #68 when we updated the crd to match new openAPI specs. The crd is auto generated from code by kubebuilder. IMHO we would need to specify that it an object type with kubebuilder annotations and regenerate the crd

**Comment by romanlytvyn** [comment]
@Demonsthere @aeneasr Would it be possible to release a new maester image version along with updated helm chart?
This issue is currently blocking us from upgrading.
