### ISSUE TITLE
Reconciler is not using Hydra admin url from spec

### ISSUE THREAD

**Issue by athak** [ory/hydra-maester#82]
**Describe the bug**

We want to deploy multiple Hydra instances and use a single maester instance. The maester instance is in namespace A and the Hydra instances and OAuth2Client definitions are on namespace B.

All OAuth2Client definitions are specifying a `hydraAdmin` block to point to the corresponding Hydra instance admin. The maester however seems to ignore the override and uses the default admin URL.

**To Reproduce**

- Deploy a single instance of the `hydra-maester` Helm chart in namespace A
- Deploy one or more instances of Hydra using the `hydra` Helm chart (with `maester.enabled` set to `false`) in namespace B
- Deploy one or more `OAuth2Client` definitions specifying the `hydraAdmin` block in the spec to point to the deployed Hydra instance services.

**Expected behavior**

The maester should use the URL from the `hydraAdmin` block of the OAuth2Client definition and should register the client with Hydra admin instance successfully.

**Environment**

- Version 0.19.3 of both Helm charts
- GKE, v1.20.8-gke.900

**Comment by piotrmsc** [comment]
Hello @athak, thanks for reporting that! I have reproduced the issue and confirm it. Without yet checking the linked PR I have also checked [this commit](https://github.com/ory/hydra-maester/commit/0ac577939c1e5167bd6ae1149d2bb87ecd1b2184) produced the issue and regression. 
I will review the PR and once fix is done will let you know ;-)

**Comment by Demonsthere** [comment]
The linked PR has been merged, can this be closed?

**Comment by piotrmsc** [comment]
yes, it was also released
